user:
  role: "user"

apis:
  movies:
    url: "https://moviesminidatabase.p.rapidapi.com"
    headers: "X-RapidAPI-Host:moviesminidatabase.p.rapidapi.com"
  countries:
    url: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"

datasource:
  url: "jdbc:sqlite:C:/Users/Usuario/AppData/Roaming/DBeaverData/workspace6/.metadata/sample-database-sqlite-1/Chinook.db"
  driver-class-name: "org.sqlite.JDBC"
